name: UI Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Configure test environment
        run: bin/generate_env && yarn db:migrate
      - name: Run your tests
        run: yarn test
        env:
          HOME: /root
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-data
          retention-days: 30
          path: |
            playwright-report/
            generated/
            prisma/dev.db
            .env

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Configure environment
        run: bin/generate_env
      - name: Build
        run: yarn build
